// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFz8UIVY9CBRzfGYZ0b_K4KidB5e-bQoU',
    appId: '1:865263829829:web:7bbabaee0b6e275be2742c',
    messagingSenderId: '865263829829',
    projectId: 'makbyar-firebase',
    authDomain: 'makbyar-firebase.firebaseapp.com',
    storageBucket: 'makbyar-firebase.appspot.com',
    measurementId: 'G-XC4JBWREYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtYFL3D3Qlg1hbEtBnuuPGlZC2nSZY9yI',
    appId: '1:865263829829:android:0dce5a41e03000f0e2742c',
    messagingSenderId: '865263829829',
    projectId: 'makbyar-firebase',
    storageBucket: 'makbyar-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj7OJduSpfoiv__ftHzXXzczCxgU4foU8',
    appId: '1:865263829829:ios:8fd73f53e3fa3e18e2742c',
    messagingSenderId: '865263829829',
    projectId: 'makbyar-firebase',
    storageBucket: 'makbyar-firebase.appspot.com',
    iosClientId: '865263829829-rodcad8q5mt8t9b0tfsg2odihes7kt7f.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationNew',
  );

}